# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [2]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
matrix = matrix + np.eye(3)
matrix

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [7]:
vec = np.array([1, 2, 3])

In [12]:
print(matrix @ vec)
print(matrix * vec)

[15. 34. 53.]
[[ 2.  4.  9.]
 [ 4. 12. 18.]
 [ 7. 16. 30.]]


In [13]:
transpose_matrix = matrix.T
transpose_matrix

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [14]:
obr_matrix = np.linalg.inv(matrix)
obr_matrix

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [15]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [17]:
values, vectors = np.linalg.eig(m)
print(values)
print(vectors)


[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [23]:
matrix = np.array([[2, 3],
              [1, 2]])
matrix
np.linalg.det(matrix)


1.0