In [1]:
import numpy as np

# matrix operations

In [5]:
A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # telephone matrix
A2 = np.random.random((3, 3)) # random matrix 3x3

In [6]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
A2

array([[0.36782374, 0.92129614, 0.412541  ],
       [0.67976973, 0.6883077 , 0.52527887],
       [0.96711566, 0.41126477, 0.93143345]])

In [9]:
A3 = np.eye(3) # identity matrix 3x3
A3 # еденицы по главной диагонали, все остальные элементы 0


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
A4 = np.zeros((3, 3)) # нулевая матрица 3x3
A4 # все элементы 0


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
A5 = np.ones((3, 3)) # единичная матрица 3x3
A5 # все элементы 1


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# транспонирование матрицы(меняет строки на столбцы)
A1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [16]:
np.transpose(A1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### определитель матрицы
    используется модуль numpy.linalg и функция det

In [19]:
np.linalg.det(A1) 

-9.51619735392994e-16

#### вычисление ранга матрицы
    используется модуль numpy.linalg и функция matrix_rank



In [20]:
np.linalg.matrix_rank(A1)

2

#### нахождение обратной матрицы
    используется модуль numpy.linalg и функция inv



In [23]:
A5 = np.array([[7,4],[5,3]])
A5




array([[7, 4],
       [5, 3]])

In [25]:
A6 = np.linalg.inv(A5)
A6



array([[ 3., -4.],
       [-5.,  7.]])

In [29]:
A5 @ A6 # умножение с помощью матричного перемножения


array([[1., 0.],
       [0., 1.]])

In [30]:
A7 = np.linalg.inv(A1)
A7 # получаются очень большие числа, скорее всего произошла ошибка

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [32]:
# не получили единичную матрицу, скорее всего произошла ошибка, это даже не ошибка просто для матрицы A1 не 
# существует обратной матрицы
A1 @ A7 

array([[ 0. ,  1. , -0.5],
       [ 0. ,  2. , -1. ],
       [ 0. ,  3. ,  2.5]])

#### собственные значения и собственные векторы
    используется модуль numpy.linalg и функции eigvals и eig





In [35]:
A8 = np.array([[-1, -6], [2, 6]])
A8

array([[-1, -6],
       [ 2,  6]])

In [38]:
np.linalg.eigvals(A8) # собственные значения

array([2., 3.])

In [39]:
np.linalg.eig(A8) # в качетве первого элемента, список собственных значений, в качестве второго элемента, список собственных векторов

EigResult(eigenvalues=array([2., 3.]), eigenvectors=array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]]))

In [40]:
res = np.linalg.eig(A8)
res2 = res[1]

In [41]:
res

EigResult(eigenvalues=array([2., 3.]), eigenvectors=array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]]))

In [42]:
res2


array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]])

In [44]:
res3 = np.transpose(res2)
res3




array([[-0.89442719,  0.4472136 ],
       [ 0.83205029, -0.5547002 ]])

In [45]:
res3[0]

array([-0.89442719,  0.4472136 ])

In [46]:
res3[1]

array([ 0.83205029, -0.5547002 ])