In [12]:
import sympy as sym

# как аналитически вычислить производную с помощью sympy

In [13]:
# теперь надо определить какие из параметров будут аналитическими
x = sym.Symbol('x')

In [14]:
3*x*(x**2+x)**3

3*x*(x**2 + x)**3

In [16]:
res=sym.diff(3*x*(x**2+x)**3,x)
res # аналитчкская производная

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

In [17]:
res.subs(x,1) # подстановка значения

132

In [2]:
3*1*(6*1 + 3)*(1**2 + 1)**2 + 3*(1**2 + 1)**3


132

# Операции с векторами, часть 1
    Условие задачи
    Задайте вектор vec2=[1,2,3,4] , используя numpy.
    В рамках задания также задан случайный вектор vec1. Выполните все поэлементные операции с векторами vec1 и vec2:

    сложение;
    вычитание из vec1 ;
    умножение;
    деление vec1.


In [3]:
import numpy as np

def seed(seed_value):
    np.random.seed(seed_value)
    vec_1 = np.random.rand(4)
    return vec_1

def vector_arithmetic(vec_1):
    
    vec_2 = np.array([1,2,3,4])
    
    addition_result = vec_1 + vec_2
    subtraction_result = vec_1 - vec_2
    elementwise_multiplication = vec_1 * vec_2
    elementwise_division = vec_1 / vec_2
    
    return vec_2, addition_result, subtraction_result, elementwise_multiplication, elementwise_division   

print(f"Поэлементная сумма векторов {seed(12)} и {vector_arithmetic(seed(12))[0]} = {vector_arithmetic(seed(12))[1]}")
print(f"Поэлементная разность векторов {seed(12)} и {vector_arithmetic(seed(12))[0]} = {vector_arithmetic(seed(12))[2]}")
print(f"Поэлементное произведение векторов {seed(12)} и {vector_arithmetic(seed(12))[0]} = {vector_arithmetic(seed(12))[3]}")
print(f"Поэлементное деление векторов {seed(12)} и {vector_arithmetic(seed(12))[0]} = {vector_arithmetic(seed(12))[4]}")

Поэлементная сумма векторов [0.15416284 0.7400497  0.26331502 0.53373939] и [1 2 3 4] = [1.15416284 2.7400497  3.26331502 4.53373939]
Поэлементная разность векторов [0.15416284 0.7400497  0.26331502 0.53373939] и [1 2 3 4] = [-0.84583716 -1.2599503  -2.73668498 -3.46626061]
Поэлементное произведение векторов [0.15416284 0.7400497  0.26331502 0.53373939] и [1 2 3 4] = [0.15416284 1.48009939 0.78994505 2.13495757]
Поэлементное деление векторов [0.15416284 0.7400497  0.26331502 0.53373939] и [1 2 3 4] = [0.15416284 0.37002485 0.08777167 0.13343485]


# задача 2
    Условие задачи
    Задайте вектор vec2=[5,4,3,2,1] , используя numpy.
    В рамках задания также задан случайный вектор vec1 . Найдите скалярное произведение векторов vec1 и vec2 .
    Прибавьте ко всем элементам вектора vec2 второй элемент вектора vec1 не используя цикл.
    Умножьте все элементы вектора vec2 на последний элемент вектора vec1 не используя цикл.

In [4]:
import numpy as np

def seed(seed_value):
    np.random.seed(seed_value)
    vec_1 = np.random.rand(5)
    return vec_1

def vector_arithmetic(vec_1):
    
    vec_2 = np.array([5,4,3,2,1])
    
    dot_product = np.dot(vec_1, vec_2) # скалярное произведение
    scalar_addition = vec_2 + vec_1[1] # прибавление второго элемента вектора vec1 к каждому элементу вектора vec2
    scalar_multiplication = vec_2 * vec_1[-1] # умножение каждого элемента вектора vec2 на последний элемент вектора vec1

    return vec_2, dot_product, scalar_addition, scalar_multiplication   

print(f"Скалярное произведение векторов {seed(12)} и {vector_arithmetic(seed(12))[0]} = {vector_arithmetic(seed(12))[1]}")
print(f"Сумма {seed(12)[1]} и {vector_arithmetic(seed(12))[0]} = {vector_arithmetic(seed(12))[2]}")
print(f"Произведение {seed(12)[-1]} и {vector_arithmetic(seed(12))[0]} = {vector_arithmetic(seed(12))[3]}")

Скалярное произведение векторов [0.15416284 0.7400497  0.26331502 0.53373939 0.01457496] и [5 4 3 2 1] = 5.6030117927614
Сумма 0.7400496965154048 и [5 4 3 2 1] = [5.7400497 4.7400497 3.7400497 2.7400497 1.7400497]
Произведение 0.014574962485419674 и [5 4 3 2 1] = [0.07287481 0.05829985 0.04372489 0.02914992 0.01457496]


In [5]:
vector_arithmetic(seed(12))

(array([5, 4, 3, 2, 1]),
 5.6030117927614,
 array([5.7400497, 4.7400497, 3.7400497, 2.7400497, 1.7400497]),
 array([0.07287481, 0.05829985, 0.04372489, 0.02914992, 0.01457496]))

# задача 3 Косинус угла между векторами
    Условие задачи
    Найдите косинус угла между заданными векторами vec1 и vec2.

    Для этого необходимо найти скалярное произведение и Евклидовы нормы каждого вектора. Результат, так называемая косинусная мера, может использоваться для определения похожести векторов.



In [ ]:
import numpy as np

def seed(seed_value):
    np.random.seed(seed_value)
    vec_1 = np.random.rand(6)
    vec_2 = np.random.rand(6)
    return vec_1, vec_2

def cosine_similarity(vec_1, vec_2):

    cosine_similarity = np.dot(vec_1, vec_2) / (np.linalg.norm(vec_1) * np.linalg.norm(vec_2))

    return cosine_similarity

print(f"Косинус угла между векторами {seed(12)[0]} и {seed(12)[1]} = {cosine_similarity(seed(12)[0], seed(12)[1])}")

# задача 4 Телефонная матрица
    Условие задачи
    Задайте телефонную mat2=[[1,2,3],[4,5,6],[7,8,9]] , используя numpy.

    В рамках задания также задана случайная матрица mat1 идентичной размерности. Выполните все поэлементные операции с векторами mat1 и mat2:

    сложение;
    вычитание из mat1 ;
    умножение;
    деление mat1 ;
    матричное умножение.


In [6]:
import numpy as np

def seed(seed_value):
    np.random.seed(seed_value)
    mat_1 = np.random.rand(3, 3)
    return mat_1

def matrix_arithmetic(mat_1):
    # Задайте телефонную матрицу [[1, 2, 3],[4, 5, 6],[7, 8, 9]], используя numpy
    # Выполните все поэлемнтные операции с матрицами mat_1 и mat_2:
    # сложение, вычитание из mat_1, умножение и деление mat_1

    mat_2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

    matrix_sum = mat_1 + mat_2
    matrix_diff = mat_1 - mat_2
    elementwise_product = mat_1 * mat_2
    elementwise_division = mat_1 / mat_2
    matrix_product = np.dot(mat_1, mat_2)

    return mat_2, matrix_sum, matrix_diff, elementwise_product, elementwise_division, matrix_product

print(f"Поэлементная сумма матриц {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[1]}")
print(f"Поэлементная разность матриц {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[2]}")
print(f"Поэлементное произведение матриц {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[3]}")
print(f"Поэлементная деление матриц {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[4]}")
print(f"Матричное умножение {seed(12)} и {matrix_arithmetic(seed(12))[0]} = {matrix_arithmetic(seed(12))[5]}")

Поэлементная сумма матриц [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] и [[1 2 3]
 [4 5 6]
 [7 8 9]] = [[1.15416284 2.7400497  3.26331502]
 [4.53373939 5.01457496 6.91874701]
 [7.90071485 8.03342143 9.95694934]]
Поэлементная разность матриц [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] и [[1 2 3]
 [4 5 6]
 [7 8 9]] = [[-0.84583716 -1.2599503  -2.73668498]
 [-3.46626061 -4.98542504 -5.08125299]
 [-6.09928515 -7.96657857 -8.04305066]]
Поэлементное произведение матриц [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] и [[1 2 3]
 [4 5 6]
 [7 8 9]] = [[0.15416284 1.48009939 0.78994505]
 [2.13495757 0.07287481 5.51248205]
 [6.30500398 0.26737142 8.61254403]]
Поэлементная деление матриц [[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]] и [[1 2 3]
 [4 5

# задача 5 Матричное умножение
    Условие задачи
    Выполните матричное умножение для матрицы mat1 размерностью 3x4 и вектора vec1 размерностью 3. На выходе должен получиться вектор vec2 размерности 4.



In [7]:
import numpy as np

def seed(seed_value):
    np.random.seed(seed_value)
    vec_1 = np.random.rand(3)
    mat_1 = np.random.rand(3, 4)

    return vec_1, mat_1

def matrix_arithmetic(vec_1, mat_1):

    vec_2 = np.dot(vec_1, mat_1)

    return vec_2

print(f"Матричное умножение {seed(12)[0]} и {seed(12)[1]} = {matrix_arithmetic(seed(12)[0],seed(12)[1])}")

ValueError: shapes (3,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)